name: 'barbearia_hadouken'
version: '1.0.0'
config-version: 2

profile: 'barbearia_hadouken'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  barbearia_teste:
    # Configura tudo como view por padrão (ou table se preferir)
    materialized: view